# Generated by Django 2.2.6 on 2019-11-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0004_auto_20191114_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_detail',
        ),
        migrations.RemoveField(
            model_name='books',
            name='isbn_no',
        ),
        migrations.RemoveField(
            model_name='books',
            name='rack_no',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='return',
            name='isbn_no',
        ),
        migrations.AlterField(
            model_name='books',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science'), ('ECE', 'Electronics & Communication'), ('CIV', 'Civil'), ('MECH', 'Mechanical'), ('EEE', 'Electrical & Electronics'), ('MBA', 'Master in Business Administration')], max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='depart',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science'), ('ECE', 'Electronics & Communication'), ('CIV', 'Civil'), ('MECH', 'Mechanical'), ('EEE', 'Electrical & Electronics'), ('MBA', 'Master in Business Administration')], max_length=3),
        ),
    ]
