# Generated by Django 2.2.6 on 2019-11-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0006_auto_20191115_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Faculty',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='emp_id',
            new_name='fac_id',
        ),
    ]
