# Generated by Django 2.2.6 on 2019-11-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0007_auto_20191125_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='fac_id',
            new_name='faculty_id',
        ),
    ]
