# Generated by Django 2.2.6 on 2019-11-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0009_auto_20191125_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
    ]
