# Generated by Django 2.2.6 on 2020-03-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0010_auto_20191125_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=4),
        ),
    ]
